version: '2'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    ports:
      - "9001:9001"
# use this command if you want to build your project within the container
#    command: mvn spring-boot:run

# using this command if you are building locally and don't want to build everytime you start your container
    command: >
              java
              -Xdebug
              -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9001
              -jar target/springboot-test-1.0.0.jar
    depends_on:
      - nginx
